version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    restart: on-failure:3
    networks:
      - bridge


  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - bridge

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - 8081:8081
    networks:
      - bridge
    depends_on:
      - redis

  nestjs:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge